name: PHPUnit test

on:
  pull_request:
    paths:
      - "project/**"
      - ".github/workflows/ci.yml"
  workflow_dispatch:

jobs:
  app_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./project
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install PHP dependencies
        uses: php-actions/composer@v6
        with:
          version: 2
          php_version: "8.3"
          php_extensions: zip
          working_dir: "project"
          interaction: no
          quiet: yes
          args: "--optimize-autoloader --ignore-platform-reqs --no-scripts"
      - name: Run phpunit
        uses: php-actions/phpunit@v3
        with:
          php_version: 8.3
          php_extensions: "zip"
          configuration: "project/phpunit.xml"
          testsuite: unit
